'use strict';

const engagements = {
    /*
        "TF_sales_accessories[DT_S]":                        "TF-sales-accessories",
        "TF_sales_accessories_audio[DT_S]":                  "TF-sales-accessories-audio",
        "TF_sales_accessories_batteries[DT_S]":              "TF-sales-accessories-batteries",
        "TF_sales_accessories_cables[DT_S]":                 "TF-sales-accessories-cables",
        "TF_sales_accessories_cases[DT_S]":                  "TF-sales-accessories-cases",
        "TF_sales_accessories[DT_O_TOL_30s]":                "TF-sales-accessories",
        "TF_sales_accessories_audio[DT_O_TOL_30s]":          "TF-sales-accessories-audio",
        "TF_sales_accessories_batteries[DT_O_TOL_30s]":      "TF-sales-accessories-batteries",
        "TF_sales_accessories_cables[DT_O_TOL_30s]":         "TF-sales-accessories-cables",
        "TF_sales_accessories_cases[DT_O_TOL_30s]":          "TF-sales-accessories-cases",
        "TF_sales_spa_accessories[DT_S]":                    "TF-sales-spa-accessories",
        "TF_sales_spa_accessories_audio[DT_S]":              "TF-sales-spa-accessories-audio",
        "TF_sales_spa_accessories_batteries[DT_S]":          "TF-sales-spa-accessories-batteries",
        "TF_sales_spa_accessories_cables[DT_S]":             "TF-sales-spa-accessories-cables",
        "TF_sales_spa_accessories_cases[DT_S]":              "TF-sales-spa-accessories-cases",
        "TF_sales_spa_accessories[DT_O_TOL_30s]":            "TF-sales-spa-accessories",
        "TF_sales_spa_accessories_audio[DT_O_TOL_30s]":      "TF-sales-spa-accessories-audio",
        "TF_sales_spa_accessories_batteries[DT_O_TOL_30s]":  "TF-sales-spa-accessories-batteries",
        "TF_sales_spa_accessories_cables[DT_O_TOL_30s]":     "TF-sales-spa-accessories-cables",
        "TF_sales_spa_accessories_cases[DT_O_TOL_30s]":      "TF-sales-spa-accessories-cases",
        "TF_care_activation[DT_S]":                          "TF-care-activation",
        "TF_care_activate_phones_landing_pho[DT_S]":         "TF-care-activate-phones-landing-pho",
        "TF_care_activate_phones_newact_sim[DT_S]":          "TF-care-activate-phones-esimnewact-sim",
        "TF_care_activate_phones_newact_esn[DT_S]":          "TF-care-activate-phones-newact-esn",
        "TF_care_activate_byop_landing_pho[DT_S]":           "TF-care-activate-byop-landing-pho",
        "TF_care_activate_byop_newact_sim[DT_S]":            "TF-care-activate-byop-esimnewact-sim",
        "TF_care_activation[DT_O_TOL_30s]":                  "TF-care-activation",
        "TF_care_activate_phones_landing_pho[DT_O_TOL_30s]": "TF-care-activate-phones-landing-pho",
        "TF_care_activate_phones_newact_sim[DT_O_TOL_30s]":  "TF-care-activate-phones-esimnewact-sim",
        "TF_care_activate_phones_newact_esn[DT_O_TOL_30s]":  "TF-care-activate-phones-newact-esn",
        "TF_care_activate_byop_landing_pho[DT_O_TOL_30s]":   "TF-care-activate-byop-landing-pho",
        "TF_care_activate_byop_newact_sim[DT_O_TOL_30s]":    "TF-care-activate-byop-esimnewact-sim",
        "TF_care_spa_activation[DT_S]":                      "TF-care-spa-activation",
        "TF_care_spa_activate_phones_lan_pho[DT_S]":         "TF-care-spa-activate-phones-lan-pho",
        "TF_care_spa_activate_phones_esi_sim[DT_S]":         "TF-care-spa-activate-phones-esi-sim",
        "TF_care_spa_activate_phones_new_esn[DT_S]":         "TF-care-spa-activate-phones-newact-esn",
        "TF_care_spa_activate_byop_lan_pho[DT_S]":           "TF-care-spa-activate-byop-lan-pho",
        "TF_care_spa_activate_byop_esi_sim[DT_S]":           "TF-care-spa-activate-byop-esi-sim",
        "TF_care_spa_activation[DT_O_TOL_30s]":              "TF-care-spa-activation",
        "TF_care_spa_activate_phones_lan_pho[DT_O_TOL_30s]": "TF-care-spa-activate-phones-lan-pho",
        "TF_care_spa_activate_phones_esi_sim[DT_O_TOL_30s]": "TF-care-spa-activate-phones-esi-sim",
        "TF_care_spa_activate_phones_new_esn[DT_O_TOL_30s]": "TF-care-spa-activate-phones-newact-esn",
        "TF_care_spa_activate_byop_lan_pho[DT_O_TOL_30s]":   "TF-care-spa-activate-byop-lan-pho",
        "TF_care_spa_activate_byop_esi_sim[DT_O_TOL_30s]":   "TF-care-spa-activate-byop-esi-sim",
        "TF_sales_deals[DT_S]":                              "TF-sales-deals",
        "TF_sales_deals_summer-time[DT_S]":                  "TF-sales-deals-summer-time",
        "TF_sales_deals_refurbished-phones[DT_S]":           "TF-sales-deals-refurbished-phones",
        "TF_sales_deals_clearance-sale[DT_S]":               "TF-sales-deals-clearance-sale",
        "TF_sales_deals_discounted-favorites[DT_S]":         "TF-sales-deals-discounted-favorites",
        "TF_sales_deals[DT_O_TOL_30s]":                      "TF-sales-deals",
        "TF_sales_deals_summer-time[DT_O_TOL_30s]":          "TF-sales-deals-summer-time",
        "TF_sales_deals_refurbished-phones[DT_O_TOL_30s]":   "TF-sales-deals-refurbished-phones",
        "TF_sales_deals_clearance-sale[DT_O_TOL_30s]":       "TF-sales-deals-clearance-sale",
        "TF_sales_deals_discounted-favorites[DT_O_TOL_30s]": "TF-sales-deals-discounted-favorites",
        "TF_sales_spa_deals[DT_S]":                          "TF-sales-spa-deals",
        "TF_sales_spa_deals_summer-time[DT_S]":              "TF-sales-spa-deals-summer-time",
        "TF_sales_spa_deals_refurb-phones[DT_S]":            "TF-sales-spa-deals-refurbished-phones",
        "TF_sales_spa_deals_clearance-sale[DT_S]":           "TF-sales-spa-deals-clearance-sale",
        "TF_sales_spa_deals_discounted-fav[DT_S]":           "TF-sales-spa-deals-discounted-favorites",
        "TF_sales_spa_deals[DT_O_TOL_30s]":                  "TF-sales-spa-deals",
        "TF_sales_spa_deals_summer-time[DT_O_TOL_30s]":      "TF-sales-spa-deals-summer-time",
        "TF_sales_spa_deals_refurb-phones[DT_O_TOL_30s]":    "TF-sales-spa-deals-refurbished-phones",
        "TF_sales_spa_deals_clearance-sale[DT_O_TOL_30s]":   "TF-sales-spa-deals-clearance-sale",
        "TF_sales_spa_deals_discounted-fav[DT_O_TOL_30s]":   "TF-sales-spa-deals-discounted-favorites",
        "TF_sales_kyop[DT_S]":                               "TF-sales-kyop",
        "TF_sales_spa_kyop[DT_S]":                           "TF-sales-spa-kyop",
        "TF_sales_kyop[DT_O_TOL_30s]":                       "TF-sales-kyop",
        "TF_sales_spa_kyop[DT_O_TOL_30s]":                   "TF-sales-spa-kyop",
        "TF_care_login[DT_S]":                               "TF-care-login",
        "TF_care_spa_login[DT_S]":                           "TF-care-spa-login",
        "TF_sales_phone[DT_S]":                              "TF-sales-phone",
        "TF_sales_smartphones[DT_S]":                        "TF-sales-smartphones",
        "TF_sales_basic-phones[DT_S]":                       "TF-sales-basic-phones",
        "TF_sales_support_hearing-aid-com[DT_S]":            "TF-sales-support-hearing-aid-comp",
        "TF_sales_phone[DT_O_TOL_30s]":                      "TF-sales-phone",
        "TF_sales_smartphones[DT_O_TOL_30s]":                "TF-sales-smartphones",
        "TF_sales_basic-phones[DT_O_TOL_30s]":               "TF-sales-basic-phones",
        "TF_sales_support_hearing-aid-com[DT_O_TOL_30s]":    "TF-sales-support-hearing-aid-comp",
        "TF_sales_spa_phone[DT_S]":                          "TF-sales-spa-phone",
        "TF_sales_spa_smartphones[DT_S]":                    "TF-sales-spa-smartphones",
        "TF_sales_spa_basic-phones[DT_S]":                   "TF-sales-spa-basic-phones",
        "TF_sales_spa_phone[DT_O_TOL_30s]":                  "TF-sales-spa-phone",
        "TF_sales_spa_smartphones[DT_O_TOL_30s]":            "TF-sales-spa-smartphones",
        "TF_sales_spa_basic-phones[DT_O_TOL_30s]":           "TF-sales-spa-basic-phones",
        "TF_sales_acp[DT_S]":                                "TF-sales-acp",
        "TF_sales_handset-protection[DT_S]":                 "TF-sales-handset-protection",
        "TF_sales_idnotify[DT_S]":                           "TF-sales-idnotify",
        "TF_sales_phone-add-ons[DT_S]":                      "TF-sales-phone-add-ons",
        "TF_sales_phone-service-plans[DT_S]":                "TF-sales-phone-service-plans",
        "TF_sales_tracfone-extras[DT_S]":                    "TF-sales-tracfone-extras",
        "TF_sales_acp[DT_O_TOL_30s]":                        "TF-sales-acp",
        "TF_sales_handset-protection[DT_O_TOL_30s]":         "TF-sales-handset-protection",
        "TF_sales_idnotify[DT_O_TOL_30s]":                   "TF-sales-idnotify",
        "TF_sales_phone-add-ons[DT_O_TOL_30s]":              "TF-sales-phone-add-ons",
        "TF_sales_phone-service-plans[DT_O_TOL_30s]":        "TF-sales-phone-service-plans",
        "TF_sales_tracfone-extras[DT_O_TOL_30s]":            "TF-sales-tracfone-extras",
        "TF_sales_spa_acp[DT_S]":                            "TF-sales-spa-acp",
        "TF_sales_spa_handset-protection[DT_S]":             "TF-sales-spa-handset-protection",
        "TF_sales_spa_idnotify[DT_S]":                       "TF-sales-spa-idnotify",
        "TF_sales_spa_phone-add-ons[DT_S]":                  "TF-sales-spa-phone-add-ons",
        "TF_sales_spa_phone-service-plans[DT_S]":            "TF-sales-spa-phone-service-plans",
        "TF_sales_spa_tracfone-extras[DT_S]":                "TF-sales-spa-tracfone-extras",
        "TF_sales_spa_acp[DT_O_TOL_30s]":                    "TF-sales-spa-acp",
        "TF_sales_spa_handset-protection[DT_O_TOL_30s]":     "TF-sales-spa-handset-protection",
        "TF_sales_spa_idnotify[DT_O_TOL_30s]":               "TF-sales-spa-idnotify",
        "TF_sales_spa_phone-add-ons[DT_O_TOL_30s]":          "TF-sales-spa-phone-add-ons",
        "TF_sales_spa_phone-service-plans[DT_O_TOL_30s]":    "TF-sales-spa-phone-service-plans",
        "TF_sales_spa_tracfone-extras[DT_O_TOL_30s]":        "TF-sales-spa-tracfone-extras",
        "TF_care_refill_refill-your-plan[DT_S]":             "TF-care-refill-refill-your-plan",
        "TF_care_refill_auto-refill[DT_S]":                  "TF-care-refill-auto-refill",
        "TF_care_spa_refill_refill-your-plan[DT_S]":         "TF-care-spa-refill-refill-your-plan",
        "TF_care_spa_refill_auto-refill[DT_S]":              "TF-care-spa-refill-auto-refill",
        "TF_sales_about_coverage[DT_S]":                     "TF-sales-about-coverage",
        "TF_sales_about_phones[DT_S]":                       "TF-sales-about-phones",
        "TF_sales_about_no-contract-plans[DT_S]":            "TF-sales-about-no-contract-plans",
        "TF_sales_about_inter-calling[DT_S]":                "TF-sales-about-international-calling",
        "TF_sales_about_rewards[DT_S]":                      "TF-sales-about-rewards",
        "TF_sales_about_apps[DT_S]":                         "TF-sales-about-apps",
        "TF_sales_about_coverage[DT_O_TOL_30s]":             "TF-sales-about-coverage",
        "TF_sales_about_phones[DT_O_TOL_30s]":               "TF-sales-about-phones",
        "TF_sales_about_no-contract[DT_O_TOL_30s]":          "TF-sales-about-no-contract-plans",
        "TF_sales_about_inter-calling[DT_O_TOL_30s]":        "TF-sales-about-international-calling",
        "TF_sales_about_rewards[DT_O_TOL_30s]":              "TF-sales-about-rewards",
        "TF_sales_about_apps[DT_O_TOL_30s]":                 "TF-sales-about-apps",
        "TF_sales_spa_about_coverage[DT_S]":                 "TF-sales-spa-about-coverage",
        "TF_sales_spa_about_phones[DT_S]":                   "TF-sales-spa-about-phones",
        "TF_sales_spa_about_no-contract-plans[DT_S]":        "TF-sales-spa-about-no-contract-plans",
        "TF_sales_spa_about_inter-calling[DT_S]":            "TF-sales-spa-about-international-calling",
        "TF_sales_spa_about_rewards[DT_S]":                  "TF-sales-spa-about-rewards",
        "TF_sales_spa_about_apps[DT_S]":                     "TF-sales-spa-about-apps",
        "TF_sales_spa_about_coverage[DT_O_TOL_30s]":         "TF-sales-spa-about-coverage",
        "TF_sales_spa_about_phones[DT_O_TOL_30s]":           "TF-sales-spa-about-phones",
        "TF_sales_spa_about_no-contract[DT_O_TOL_30s]":      "TF-sales-spa-about-no-contract-plans",
        "TF_sales_spa_about_inter-calling[DT_O_TOL_30s]":    "TF-sales-spa-about-international-calling",
        "TF_sales_spa_about_rewards[DT_O_TOL_30s]":          "TF-sales-spa-about-rewards",
        "TF_sales_spa_about_apps[DT_O_TOL_30s]":             "TF-sales-spa-about-apps",
        "TF_care_support_contact-us[DT_E]":                  "TF-care-support-contact-us",
        "TF_care_support_contact_us_showchat[DT_S]":         "TF-care-support-contact-us-showchat",
        "TF_care_support_contact_us_botchat[DT_S]":          "TF-care-support-contact-us-botchat",
        "TF_care_support_contact_us_FBMchat[DT_S]":          "TF-care-support-contact-us-FBMchat",
        "TF_care_support_contact_us_showchat[DT_O_TOL_0s]":  "TF-care-support-contact-us-showchat",
        "TF_care_support_contact_us_botchat[DT_O_TOL_0s]":   "TF-care-support-contact-us-botchat",
        "TF_care_support_contact_us_FBMchat[DT_O_TOL_0s]":   "TF-care-support-contact-us-FBMchat",
        "TF_care_spa_support_contact_us[DT_E]":              "TF-care-spa-support-contact-us",
        "TF_care_spa_support_contact_us_showchat[DT_S]":     "TF-care-spa-support-contact-us",
        "TF_care_spa_support_contact_us_botchat[DT_S]":      "TF-care-spa-support-contact-us-botchat",
        "TF_care_spa_support_contact_us_FBMchat[DT_S]":      "TF-care-spa-support-contact-us-FBMchat",
        "TF_care_spa_contact_us[DT_O_TOL_0s]":               "TF-care-spa-support-contact-us",
        "TF_care_spa_contact_us_botchat[DT_O_TOL_0s]":       "TF-care-spa-support-contact-us-botchat",
        "TF_care_spa_contact_us_FBMchat[DT_O_TOL_0s]":       "TF-care-spa-support-contact-us-FBMchat",
        "TF_sales_mobile-lp-chat[SP_S]":                     "TF-sales-mobile-lp-chat",
        "TF_sales_shop_cart[DT_S]":                          "TF-sales-shop-cart",
        "TF_sales_shop_checkout[DT_S]":                      "TF-sales-shop-checkout",
        "TF_sales_mobile-lp-chat[SP_S_TOL_0s]":              "TF-sales-mobile-lp-chat",
        "TF_sales_shop_cart[DT_O_TOL_40s]":                  "TF-sales-shop-cart",
        "TF_sales_shop_checkout[DT_O_TOL_40s]":              "TF-sales-shop-checkout",
        "TF_sales_products_plansservices_phone[DT_S]":       "TF-sales-products-plansservices-phone",
        "TF_sales_phones_pdp[DT_S]":                         "TF-sales-phone-pdp",
        "TF_sales_phones_pdp[DT_S_TOL_40s]":                 "TF-sales-phone-pdp",
        "GS_care_wps_portal_home_contact[DT_E]":             "GS-care-wps-portal-home-contact",
        "GS_care_contactus_611611[DT_S]":                    "GS-care-contactus-611611",
        "GS_care_wps_portal_home_contact_bot[DT_S]":         "GS-care-wps-portal-home-contact-bot",
        "GS_care_wps_portal_home_contact_fbm[DT_S]":         "GS-care-wps-portal-home-contact-fbmchat",
        "GS_care_contactus_611611[DT_O_TOL_0s]":             "GS-care-contactus-611611",
        "GS_care_wps_portal_home_contact_bot[DT_O_TOL_0s]":  "GS-care-wps-portal-home-contact-bot",
        "GS_care_wps_portal_home_contact_fbm[DT_O_TOL_0s]":  "GS-care-wps-portal-home-contact-fbmchat",
        "GS_care_spa_wps_portal_home_contact[DT_E]":         "GS-care-spa-wps-portal-home-contact",
        "GS_care_spa_contactus_611611[DT_S]":                "GS-care-spa-contactus-611611",
        "GS_care_spa_wps_portal_home_contact_bot[DT_S]":     "GS-care-spa-wps-portal-home-contact-bot",
        "GS_care_spa_wps_portal_home_contact_fbm[DT_S]":     "GS-care-spa-wps-portal-home-contact-fbmchat",
        "GS_care_spa_contactus_611611[DT_O_TOL_0s]":         "GS-care-spa-contactus-611611",
        "GS_care_spa_wps_portal_contact_bot[DT_O_TOL_0s]":   "GS-care-spa-wps-portal-home-contact-bot",
        "GS_care_spa_wps_portal_contact_fbm[DT_O_TOL_0s]":   "GS-care-spa-wps-portal-home-contact-fbmchat",
        "NT_care_contactus[DT_S]":                           "NT-care-contactus",
        "NT_care_contactus[DT_E]":                           "NT-care-contactus",
        "NT_care_serviceplan[DT_S]":                         "NT-care-serviceplan",
        "NT_care_autorefill[DT_S]":                          "NT-care-autorefill",
        "NT_sales_shop_ild[DT_S]":                           "NT-sales-shop-ild",
        "NT_care_contactus_showchat[DT_S]":                  "NT-care-contactus-showchat",
        "NT_care_contactus_botchat[DT_S]":                   "NT-care-contactus-botchat",
        "NT_care_contactus_FBMchat[DT_S]":                   "NT-care-contactus-FBMchat",
        "NT_care_contactus_showchat[DT_O_TOL_0s]":           "NT-care-contactus-showchat",
        "NT_care_contactus_botchat[DT_O_TOL_0s]":            "NT-care-contactus-botchat",
        "NT_care_contactus_FBMchat[DT_O_TOL_0s]":            "NT-care-contactus-FBMchat",
        "NT_care_mobilechat[SP_S]":                          "NT-care-mobilechat",
        "NT_care_mobilechat[SP_O_TOL_0s]":                   "NT-care-mobilechat",
        "NT_care_spa_contactus[DT_E]":                       "NT-care-spa-contactus",
        "NT_care_spa_serviceplan[DT_S]":                     "NT-care-spa-serviceplan",
        "NT_care_spa_autorefill[DT_S]":                      "NT-care-spa-autorefill",
        "NT_care_spa_contactus_showchat[DT_S]":              "NT-care-spa-contactus-showchat",
        "NT_care_spa_contactus_botchat[DT_S]":               "NT-care-spa-contactus-botchat",
        "NT_care_spa_contactus_FBMchat[DT_S]":               "NT-care-spa-contactus-FBMchat",
        "NT_care_spa_contactus_showchat[DT_O_TOL_0s]":       "NT-care-spa-contactus-showchat",
        "NT_care_spa_contactus_botchat[DT_O_TOL_0s]":        "NT-care-spa-contactus-botchat",
        "NT_care_spa_contactus_FBMchat[DT_O_TOL_0s]":        "NT-care-spa-contactus-FBMchat",
        "NT_care_spa_shop_ild[DT_S]":                        "NT-care-spa-shop-ild",
        "NT_care_spa_mobilechat[DT_S]":                      "NT-care-spa-mobilechat",
        "NT_care_spa_mobilechat[SP_O_TOL_0s]":               "NT-care-spa-mobilechat",
    */


    "DP_TBV[DT_E]":                                     "DP-Care-TBV",
    "DP_AR[DT_E]":                                      "DP-Care-AR",
    "ST_5g[DT_S]":                                      "ST-5g",
    "ST_5g-lte-home-internet[DT_S]":                    "ST-5g-lte-home-internet",
    "ST_5g-lte-home-internet[DT_S_TOL-30s]":            "ST-5g-lte-home-internet",
    "ST_accessories_audio[DT_S]":                       "ST-accessories-audio",
    "ST_accessories_audio[DT_S_TOL-30s]":               "ST-accessories-audio",
    "ST_accessories_batteries[DT_S]":                   "ST-accessories-batteries",
    "ST_accessories_batteries[DT_S_TOL-30s]":           "ST-accessories-batteries",
    "ST_accessories_cables[DT_S]":                      "ST-accessories-cables",
    "ST_accessories_cables[DT_S_TOL-30s]":              "ST-accessories-cables",
    "ST_accessories_cases-protection[DT_S]":            "ST-accessories-cases-protection",
    "ST_accessories_cases-protection[DT_S_TOL-30s]":    "ST-accessories-cases-protection",
    "ST_acp[DT_S]":                                     "ST-acp",
    "ST_acp[DT_S_TOL-30s]":                             "ST-acp",
    "ST_activate.byop.landing.phoneno[DT_S]":           "ST-activate.byop.landing.phoneno",
    "ST_activate.device.landing.esn[DT_S]":             "ST-activate.device.landing.esn",
    "ST_activate.phones.landing.phoneno[DT_S]":         "ST-activate.phones.landing.phoneno",
    "ST_all-accessories[DT_S]":                         "ST-all-accessories",
    "ST_all-accessories[DT_S_TOL-30s]":                 "ST-all-accessories",
    "ST_all-devices[DT_S]":                             "ST-all-devices",
    "ST_all-devices[DT_S_TOL-30s]":                     "ST-all-devices",
    "ST_all-phones[DT_S]":                              "ST-all-phones",
    "ST_all-phones[DT_S_TOL-30s]":                      "ST-all-phones",
    "ST_all-plans[DT_S]":                               "ST-all-plans",
    "ST_all-plans[DT_S_TOL-30s]":                       "ST-all-plans",
    "ST_deals_all-deals[DT_S]":                         "ST-deals-all-deals",
    "ST_deals_all-deals[DT_S_TOL-30s]":                 "ST-deals-all-deals",
    "ST_deals_clearance-sale[DT_S]":                    "ST-deals-clearance-sale",
    "ST_deals_clearance-sale[DT_S_TOL-30s]":            "ST-deals-clearance-sale",
    "ST_deals_holiday_market-phones[DT_S]":             "ST-deals-holiday-marketplace-phones",
    "ST_deals_holiday_market-phones[DT_S_TOL-30s]":     "ST-deals-holiday-marketplace-phones",
    "ST_deals_holiday_summer-time[DT_S]":               "ST-deals-holiday-summer-time",
    "ST_deals_holiday_summer-time[DT_S_TOL-30s]":       "ST-deals-holiday-summer-time",
    "ST_deals_popular-deals[DT_S]":                     "ST-deals-popular-deals",
    "ST_deals_popular-deals[DT_S_TOL-30s]":             "ST-deals-popular-deals",
    "ST_deals_refurbished-phones[DT_S]":                "ST-deals-refurbished-phones",
    "ST_deals_refurbished-phones[DT_S_TOL-30s]":        "ST-deals-refurbished-phones",
    "ST_devices_home-internet[DT_S]":                   "ST-devices-home-internet",
    "ST_devices_home-internet[DT_S_TOL-30s]":           "ST-devices-home-internet",
    "ST_devices_phone-sim-cards[DT_S]":                 "ST-devices-phone-sim-cards",
    "ST_devices_phone-sim-cards[DT_S_TOL-30s]":         "ST-devices-phone-sim-cards",
    "ST_devices_tablet-sim-cards[DT_S]":                "ST-devices-tablet-sim-cards",
    "ST_devices_tablet-sim-cards[DT_S_TOL-30s]":        "ST-devices-tablet-sim-cards",
    "ST_devices_wifi-hotspots[DT_S]":                   "ST-devices-wifi-hotspots",
    "ST_devices_wifi-hotspots[DT_S_TOL-30s]":           "ST-devices-wifi-hotspots",
    "ST_extras_cloud-services[DT_S_TOL-30s]":           "ST-extras-cloud-services",
    "ST_extras_idnotify[DT_S_TOL-30s]":                 "ST-extras-idnotify",
    "ST_extras_intl-long-distance[DT_S_TOL-30s]":       "ST-extras-international-long-distance",
    "ST_handset-protection_mobile-prtct[DT_S]":         "ST-handset-protection-mobile-protect",
    "ST_handset-protection_mobile-prtct[DT_S_TOL-30s]": "ST-handset-protection-mobile-protect",
    "ST_more-options_phone-payment-plan[DT_S]":         "ST-more-options-phone-payment-plan",
    "ST_more-options_phone-payment-plan[DT_S_TOL-30s]": "ST-more-options-phone-payment-plan",
    "ST_more-options_trade-in-program[DT_S]":           "ST-more-options-trade-in-program",
    "ST_more-options_trade-in-program[DT_S_TOL-30s]":   "ST-more-options-trade-in-program",
    "ST_phones_5g-phones[DT_S]":                        "ST-phones-5g-phones",
    "ST_phones_5g-phones[DT_S_TOL-30s]":                "ST-phones-5g-phones",
    "ST_phones_android[DT_S]":                          "ST-phones-android",
    "ST_phones_android[DT_S_TOL-30s]":                  "ST-phones-android",
    "ST_phones_basic-phones[DT_S]":                     "ST-phones-basic-phones",
    "ST_phones_basic-phones[DT_S_TOL-30s]":             "ST-phones-basic-phones",
    "ST_phones_home-phones[DT_S]":                      "ST-phones-home-phones",
    "ST_phones_home-phones[DT_S_TOL-30s]":              "ST-phones-home-phones",
    "ST_phones_ios-phones[DT_S]":                       "ST-phones-ios-phones",
    "ST_phones_ios-phones[DT_S_TOL-30s]":               "ST-phones-ios-phones",
    "ST_plans_add-ons[DT_S]":                           "ST-plans-add-ons",
    "ST_plans_add-ons[DT_S_TOL-30s]":                   "ST-plans-add-ons",
    "ST_plans_home-internet-plans[DT_S]":               "ST-plans-home-internet-plans",
    "ST_plans_home-internet-plans[DT_S_TOL-30s]":       "ST-plans-home-internet-plans",
    "ST_plans_home-phones[DT_S]":                       "ST-plans-home-phones",
    "ST_plans_home-phones[DT_S_TOL-30s]":               "ST-plans-home-phones",
    "ST_plans_hotspots[DT_S]":                          "ST-plans-hotspots",
    "ST_plans_hotspots[DT_S_TOL-30s]":                  "ST-plans-hotspots",
    "ST_plans_tablets[DT_S]":                           "ST-plans-tablets",
    "ST_plans_tablets[DT_S_TOL-30s]":                   "ST-plans-tablets",
    "ST_plans_wireless-phones[DT_S]":                   "ST-plans-wireless-phones",
    "ST_plans_wireless-phones[DT_S_TOL-30s]":           "ST-plans-wireless-phones",
    "ST_refill_auto-refill[DT_S]":                      "ST-refill-auto-refill",
    "ST_refill_refill-your-plan[DT_S]":                 "ST-refill-refill-your-plan",
    "ST_spa_5g[DT_S]":                                  "ST-spa-5g",
    "ST_whyst_coverage[DT_S]":                          "ST-whyst-coverage",
    "ST_whyst_coverage[DT_S_TOL-30s]":                  "ST-whyst-coverage",
    "ST_whyst_keep-your-own-phone[DT_S]":               "ST-whyst-keep-your-own-phone",
    "ST_whyst_keep-your-own-phone[DT_S_TOL-30s]":       "ST-whyst-keep-your-own-phone",
    "ST_whyst_phones[DT_S]":                            "ST-whyst-phones",
    "ST_whyst_phones[DT_S_TOL-30s]":                    "ST-whyst-phones",
    "ST_whyst_plans[DT_S]":                             "ST-whyst-plans",
    "ST_whyst_plans[DT_S_TOL-30s]":                     "ST-whyst-plans",
    "SL_care[DT_S]":                                    "SL-Care",
    "SL_about_us[DT_S]":                                "SL-care-about-us",
    "SL_contact_us[DT_E]":                              "SL-contact-us",
    "SL_contact_us_showchat[DT_S]":                     "SL-contact-us-showchat",
    "SL_contact_us_botchat[DT_S]":                      "SL-contact-us-botchat",
    "SL_contact_us_FBMchat[DT_S]":                      "SL-contact-us-FBMchat",
    "SL_contact_us_showchat[DT_O_TOL_0s]":              "SL-contact-us-showchat",
    "SL_contact_us_botchat[DT_O_TOL_0s]":               "SL-contact-us-botchat",
    "SL_contact_us_FBMchat[DT_O_TOL_0s]":               "SL-contact-us-FBMchat",
    "SL_spa_contact_us[DT_E]":                          "SL-spa-contact-us",
    "SL_spa_contact_us_showchat[DT_S]":                 "SL-spa-contact-us-showchat",
    "SL_spa_contact_us_botchat[DT_S]":                  "SL-spa-contact-us-botchat",
    "SL_spa_contact_us_FBMchat[DT_S]":                  "SL-spa-contact-us-FBMchat",
    "SL_spa_contact_us_showchat[DT_O_TOL_0s]":          "SL-spa-contact-us-showchat",
    "SL_spa_contact_us_botchat[DT_O_TOL_0s]":           "SL-spa-contact-us-botchat",
    "SL_spa_contact_us_FBMchat[DT_O_TOL_0s]":           "SL-spa-contact-us-FBMchat",
    "SM_shop_simplemobile_phones[DT_S]":                "SM-sales-shop-simplemobile-phones",
    "SM_sales_activation_byopcollectsim[DT_S]":         "SM-sales-activation-byopcollectsim",
    "SM_sales_serviceplan[DT_S]":                       "SM-sales-serviceplan",
    "SM_sales_shop_simplemobile_acc[DT_S]":             "SM-sales-shop-simplemobile-accessories",
    "SM_sales_shop_simplemobile_accessories[DT_S]":     "SM-sales-shop-simplemobile-accessories",
    "SM_sales_why-simple-mobile_intl[DT_S]":            "SM-sales-why-simple-mobile-intl",
    "SM_sales_shop_simplemobile_dat[DT_S]":             "SM-sales-shop-simplemobile-datadevices",
    "SM_sales_acp[DT_S]":                               "SM-sales-acp",
    "SM_care_protectyourphones_landing[DT_S]":          "SM-care-protectyourphones-landing",
    "SM_care_collectminpinpromo[DT_S]":                 "SM-care-collectminpinpromo",
    "SM_care_autorefill[DT_S]":                         "SM-care-autorefill",
    "SM_care_serviceplan_addons[DT_S]":                 "SM-care-serviceplan-addons",
    "SM_care_activation_selectdevice[DT_S]":            "SM-care-activation-selectdevice",
    "SM_care_shop_simplemobile_deals[DT_S]":            "SM-sales-shop-simplemobile-deals",
    "SM_care_why-sm[DT_S]":                             "SM-sales-why-sm",
    "SM_care_why-sm_no-contracts[DT_S]":                "SM-sales-why-sm-no-contracts",
    "SM_care_why-sm_unlimited-data[DT_S]":              "SM-sales-why-sm-unlimited-data",
    "SM_care_why-sm_keep-your-phone[DT_S]":             "SM-sales-why-sm-keep-your-phone",
    "SM_care_why-sm_lease-your-phone[DT_S]":            "SM-sales-why-sm-lease-your-phone",
    "SM_care_why-simple-mobile_intl[DT_S]":             "SM-sales-why-simple-mobile-intl",
    "SM_care_why-simple-mobile_serviceplan[DT_S]":      "SM-sales-why-simple-mobile-serviceplan",
    "SM_care_rewards[DT_S]":                            "SM-care-rewards",
    "SM_care_myaccount_login_collectusername[DT_S]":    "SM-care-myaccount-login-collectusername",
    "SM_sales_activation_byopcollectsim[DT_S_TOL-30s]": "SM-sales-activation-byopcollectsim",
    "SM_sales_serviceplan[DT_S_TOL-30s]":               "SM-sales-serviceplan",
    "SM_sales_shop_sm_accessories[DT_S_TOL-30s]":       "SM-sales-shop-simplemobile-accessories",
    "SM_sales_why-simple-mobile_intl[DT_S_TOL-30s]":    "SM-sales-why-simple-mobile-intl",
    "SM_sales_shop_sM_datadevices[DT_S_TOL-30s]":       "SM-sales-shop-simplemobile-datadevices",
    "SM_sales_acp[DT_S_TOL-30s]":                       "SM-sales-acp",
    "SM_sales_shop_simplemobile_deals[DT_S_TOL-30s]":   "SM-sales-shop-simplemobile-deals",
    "SM_sales_why-sm[DT_S_TOL-30s]":                    "SM-sales-why-sm",
    "SM_sales_why-sm_no-contracts[DT_S_TOL-30s]":       "SM-sales-why-sm-no-contracts",
    "SM_sales_why-sm_unlimited-data[DT_S_TOL-30s]":     "SM-sales-why-sm-unlimited-data",
    "SM_sales_why-sm_keep-your-phone[DT_S_TOL-30s]":    "SM-sales-why-sm-keep-your-phone",
    "SM_sales_why-sm_lease-your-phone[DT_S_TOL-30s]":   "SM-sales-why-sm-lease-your-phone",
    "SM_sales_protectyourphones_landing[DT_S_TOL-30s]": "SM-sales-protectyourphones-landing",
    "SM_sales_why-sm_serviceplan[DT_S_TOL-30s]":        "SM-sales-why-simple-mobile-serviceplan",
    "SM_spa_shop_sm_phones[DT_S]":                      "SM-spa-shop-simplemobile-phones",
    "SM_sales_spa_activation_byopcollectsim[DT_S]":     "SM-sales-spa-activation-byopcollectsim",
    "SM_sales_spa_serviceplan[DT_S]":                   "SM-sales-spa-serviceplan",
    "SM_sales_spa_why-simple-mobile_intl[DT_S]":        "SM-sales-spa-why-simple-mobile-intl",
    "SM_care_spa_shop_simplemobile_lea[DT_S]":          "SM-care-spa-shop-en-sim-lea",
    "SM_care_spa_protectyourphones_landing[DT_S]":      "SM-care-spa-protectyourphones-landing",
    "SM_sales_spa_shop_simplemobile_dat[DT_S]":         "SM-sales-spa-shop-simplemobile-dat",
    "SM_sales_spa_acp[DT_S]":                           "SM-sales-spa-acp",
    "SM_care_spa_collectminpinpromo[DT_S]":             "SM-care-spa-collectminpinpromo",
    "SM_care_spa_autorefill[DT_S]":                     "SM-care-spa-autorefill",
    "SM_care_spa_serviceplan_addons[DT_S]":             "SM-care-spa-serviceplan-addons",
    "SM_care_spa_activation_selectdevice[DT_S]":        "SM-care-spa-activation-selectdevice",
    "SM_sales_spa_why-sm[DT_S]":                        "SM-sales-spa-why-sm",
    "SM_sales_spa_why-sm_no-contracts[DT_S]":           "SM-sales-spa-why-sm-no-contracts",
    "SM_sales_spa_why-sm_unlimited-data[DT_S]":         "SM-sales-spa-why-sm-unlimited-data",
    "SM_sales_spa_why-sm_keep-your-phone[DT_S]":        "SM-sales-spa-why-sm-keep-your-phone",
    "SM_sales_spa_why-sm_lease-your-phone[DT_S]":       "SM-sales-spa-why-sm-lease-your-phone",
    "SM_sales_spa_protectyourphones_landing[DT_S]":     "SM-sales-spa-protectyourphones-landing",
    "SM_sales_spa_why-sm_intl[DT_S]":                   "SM-sales-spa-why-simple-mobile-intl",
    "SM_sales_spa_why-sm_serviceplan[DT_S]":            "SM-sales-spa-why-simple-mobile-serviceplan",
    "SM_care_spa_rewards[DT_S]":                        "SM-care-spa-rewards",
    "SM_care_spa_myaccount_login_col[DT_S]":            "SM-care-spa-myaccount-login-col",
    "SM_sales_spa_shop_sm_phones[DT_S_TOL-30s]":        "SM-spa-shop-simplemobile-phones",
    "SM_sales_spa_activation_byopsim[DT_S_TOL-30s]":    "SM-sales-spa-activation-byopcollectsim",
    "SM_sales_spa_serviceplan[DT_S_TOL-30s]":           "SM-sales-spa-serviceplan",
    "SM_sales_spa_why-sm_intl[DT_S_TOL-30s]":           "SM-sales-spa-why-simple-mobile-intl",
    "SM_sales_spa_shop_sm_dat[DT_S_TOL-30s]":           "SM-sales-spa-shop-simplemobile-dat",
    "SM_sales_spa_acp[DT_S_TOL-30s]":                   "SM-sales-spa-acp",
    "SM_sales_spa_why-sm[DT_S_TOL-30s]":                "SM-sales-spa-why-sm",
    "SM_sales_spa_why-sm_no-contracts[DT_S_TOL-30s]":   "SM-sales-spa-why-sm-no-contracts",
    "SM_sales_spa_why-sm_unlimited-data[DT_S_TOL-30s]": "SM-sales-spa-why-sm-unlimited-data",
    "SM_sales_spa_why-sm_keep-phone[DT_S_TOL-30s]":     "SM-sales-spa-why-sm-keep-your-phone",
    "SM_sales_spa_why-sm_lease-phone[DT_S_TOL-30s]":    "SM-sales-spa-why-sm-lease-your-phone",
    "SM_sales_spa_protectphones_landing[DT_S_TOL-30s]": "SM-sales-spa-protectyourphones-landing",
    "SM_sales_spa_why-sm_serviceplan[DT_S_TOL-30s]":    "SM-sales-spa-why-simple-mobile-serviceplan",
    "TBV_sales_plans[DT_S]":                            "TBV-sales-plans",
    "TBV_sales_all-phones[DT_S]":                       "TBV-sales-all-phones",
    "TBV_sales_kyop[DT_S]":                             "TBV-sales-kyop",
    "TBV_sales_smartphones[DT_S]":                      "TBV-sales-smartphones",
    "TBV_sales_basic-phones[DT_S]":                     "TBV-sales-basic-phones",
    "TBV_sales_accessories[DT_S]":                      "TBV-sales-accessories",
    "TBV_sales_deals[DT_S]":                            "TBV-sales-deals",
    "TBV_sales_extras_disney-plus[DT_S]":               "TBV-sales-extras-disney-plus",
    "TBV_care_plans_global-calling-card[DT_S]":         "TBV-care-plans-global-calling-card",
    "TBV_care_intl-calling-destinations[DT_S]":         "TBV-care-international-calling-destinations",
    "TBV_care_refill_refill-your-plan[DT_S]":           "TBV-care-refill-refill-your-plan",
    "TBV_care_activation[DT_S]":                        "TBV-care-activation",
    "TBV_care_activate-phones-landing-pho[DT_S]":       "TBV-care-activate-phones-landing-phoneno",
    "TBV_care_activate-byop-landing-pho[DT_S]":         "TBV-care-activate-byop-landing-phoneno",
    "TBV_care_activate-device-landing-esn[DT_S]":       "TBV-care-activate-device-landing-esn",
    "TBV_sales_about_coverage[DT_S]":                   "TBV-sales-about-coverage",
    "TBV_sales_about_no-contract-plans[DT_S]":          "TBV-sales-about-no-contract-phone-plans",
    "TBV_sales_about_prepaid-phones[DT_S]":             "TBV-sales-about-prepaid-phones",
    "TBV_care_my-account_my-rewards[DT_S]":             "TBV-care-my-account-my-rewards",
    "TBV_sales_plans[DT_S_TOL-30s]":                    "TBV-sales-plans",
    "TBV_sales_all-phones[DT_S_TOL-30s]":               "TBV-sales-all-phones",
    "TBV_sales_kyop[DT_S_TOL-30s]":                     "TBV-sales-kyop",
    "TBV_sales_smartphones[DT_S_TOL-30s]":              "TBV-sales-smartphones",
    "TBV_sales_basic-phones[DT_S_TOL-30s]":             "TBV-sales-basic-phones",
    "TBV_sales_accessories[DT_S_TOL-30s]":              "TBV-sales-accessories",
    "TBV_sales_deals[DT_S_TOL-30s]":                    "TBV-sales-deals",
    "TBV_sales_extras_disney-plus[DT_S_TOL-30s]":       "TBV-sales-extras-disney-plus",
    "TBV_care_plans_glob-call-car[DT_S_TOL-30s]":       "TBV-care-plans-global-calling-card",
    "TBV_sales_about_coverage[DT_S_TOL-30s]":           "TBV-sales-about-coverage",
    "TBV_sales_about_no-contract[DT_S_TOL-30s]":        "TBV-sales-about-no-contract-phone-plans",
    "TBV_sales_about_prepaid-pho[DT_S_TOL-30s]":        "TBV-sales-about-prepaid-phones",
    "TBV_sales_spa_plans[DT_S]":                        "TBV-sales-plans",
    "TBV_sales_spa_all-phones[DT_S]":                   "TBV-sales-all-phones",
    "TBV_sales_spa_kyop[DT_S]":                         "TBV-sales-kyop",
    "TBV_sales_spa_smartphones[DT_S]":                  "TBV-sales-smartphones",
    "TBV_sales_spa_basic-phones[DT_S]":                 "TBV-sales-basic-phones",
    "TBV_sales_spa_accessories[DT_S]":                  "TBV-sales-accessories",
    "TBV_sales_spa_deals[DT_S]":                        "TBV-sales-deals",
    "TBV_sales_spa_extras_disney-plus[DT_S]":           "TBV-sales-extras-disney-plus",
    "TBV_care_spa_plans_global-calling-card[DT_S]":     "TBV-care-plans-global-calling-card",
    "TBV_care_spa_intl-calling-destinations[DT_S]":     "TBV-care-international-calling-destinations",
    "TBV_care_spa_refill_refill-your-plan[DT_S]":       "TBV-care-refill-refill-your-plan",
    "TBV_care_spa_activation[DT_S]":                    "TBV-care-activation",
    "TBV_care_spa_activate-phones-landing-pho[DT_S]":   "TBV-care-activate-phones-landing-phoneno",
    "TBV_care_spa_activate-byop-landing-pho[DT_S]":     "TBV-care-activate-byop-landing-phoneno",
    "TBV_care_spa_activate-device-landing-esn[DT_S]":   "TBV-care-activate-device-landing-esn",
    "TBV_sales_spa_about_coverage[DT_S]":               "TBV-sales-about-coverage",
    "TBV_sales_spa_about_no-contract-plans[DT_S]":      "TBV-sales-about-no-contract-phone-plans",
    "TBV_sales_spa_about_prepaid-phones[DT_S]":         "TBV-sales-about-prepaid-phones",
    "TBV_care_spa_my-account_my-rewards[DT_S]":         "TBV-care-my-account-my-rewards",
    "TBV_sales_spa_plans[DT_S_TOL-30s]":                "TBV-sales-plans",
    "TBV_sales_spa_all-phones[DT_S_TOL-30s]":           "TBV-sales-all-phones",
    "TBV_sales_spa_kyop[DT_S_TOL-30s]":                 "TBV-sales-kyop",
    "TBV_sales_spa_smartphones[DT_S_TOL-30s]":          "TBV-sales-smartphones",
    "TBV_sales_spa_basic-phones[DT_S_TOL-30s]":         "TBV-sales-basic-phones",
    "TBV_sales_spa_accessories[DT_S_TOL-30s]":          "TBV-sales-accessories",
    "TBV_sales_spa_deals[DT_S_TOL-30s]":                "TBV-sales-deals",
    "TBV_sales_spa_extras_disney-plus[DT_S_TOL-30s]":   "TBV-sales-extras-disney-plus",
    "TBV_care_spa_plans_glob-call-car[DT_S_TOL-30s]":   "TBV-care-plans-global-calling-card",
    "TBV_sales_spa_about_coverage[DT_S_TOL-30s]":       "TBV-sales-about-coverage",
    "TBV_sales_spa_about_no-contract[DT_S_TOL-30s]":    "TBV-sales-about-no-contract-phone-plans",
    "TBV_sales_spa_about_prepaid-pho[DT_S_TOL-30s]":    "TBV-sales-about-prepaid-phones",
    "TBV_care_mobilechat[SP_S]":            			"TBV-care-mobilechat",
    "TBV_care_mobilechat[SP_O_TOL_0s]":            		"TBV-care-mobilechat",

    "ST_care_support_contact_us[DT_E]":                 "ST-care-support-contact-us",
    "ST_care_support_contact_us_showchat[DT_S]":        "ST-care-support-contact-us-showchat",
    "ST_care_support_contact_us_botchat[DT_S]":         "ST-care-support-contact-us-botchat",
    "ST_care_support_contact_us_FBMchat[DT_S]":         "ST-care-support-contact-us-FBMchat",
    "ST_care_support_contact_us_showchat[DT_O_TOL_0s]": "ST-care-support-contact-us-showchat",
    "ST_care_support_contact_us_botchat[DT_O_TOL_0s]":  "ST-care-support-contact-us-botchat",
    "ST_care_support_contact_us_FBMchat[DT_O_TOL_0s]":  "ST-care-support-contact-us-FBMchat",
    "ST_spa_contact_us[DT_E]":                          "ST-care-spa-support-contact-us",
    "ST_spa_contact_us_showchat[DT_S]":                 "ST-care-spa-support-contact-us-showchat",
    "ST_spa_contact_us_botchat[DT_S]":                  "ST-care-spa-support-contact-us-botchat",
    "ST_spa_contact_us_FBMchat[DT_S]":                  "ST-care-spa-support-contact-us-FBMchat",
    "ST_spa_contact_us_showchat[DT_O_TOL_0s]":          "ST-care-spa-support-contact-us-showchat",
    "ST_spa_contact_us_botchat[DT_O_TOL_0s]":           "ST-care-spa-support-contact-us-botchat",
    "ST_spa_contact_us_FBMchat[DT_O_TOL_0s]":           "ST-care-spa-support-contact-us-FBMchat",

    "SM_care_mobilechat[SP_S]":			                "SM-care-mobilechat",
    "SM_care_mobilechat[SP_O_TOL-0s]":			        "SM-care-mobilechat",
    "SM_contact-us[DT_E]":                              "SM-contact-us",
    "SM_contact_us_showchat[DT_S]":                     "SM-contact-us-showchat",
    "SM_contact_us_botchat[DT_S]":                      "SM-contact-us-botchat",
    "SM_contact_us_FBMchat[DT_S]":                      "SM-contact-us-FBMchat",
    "SM_contact_us_showchat[DT_O_TOL_0s]":              "SM-contact-us-showchat",
    "SM_contact_us_botchat[DT_O_TOL_0s]":               "SM-contact-us-botchat",
    "SM_contact_us_FBMchat[DT_O_TOL_0s]":               "SM-contact-us-FBMchat",
    "SM_spa_contact_us[DT_E]":                          "SM-spa-contact-us",
    "SM_spa_contact_us_showchat[DT_S]":                 "SM-spa-contact-us-showchat",
    "SM_spa_contact_us_botchat[DT_S]":                  "SM-spa-contact-us-botchat",
    "SM_spa_contact_us_FBMchat[DT_S]":                  "SM-spa-contact-us-FBMchat",
    "SM_spa_contact_us_showchat[DT_O_TOL_0s]":          "SM-spa-contact-us-showchat",
    "SM_spa_contact_us_botchat[DT_O_TOL_0s]":           "SM-spa-contact-us-botchat",
    "SM_spa_contact_us_FBMchat[DT_O_TOL_0s]":           "SM-spa-contact-us-FBMchat",
    "TBV_contact-us[DT_E]":                             "TBV-contact-us",
    "TBV_contact_us_showchat[DT_S]":                    "TBV-contact-us-showchat",
    "TBV_contact_us_botchat[DT_S]":                     "TBV-contact-us-botchat",
    "TBV_contact_us_FBMchat[DT_S]":                     "TBV-contact-us-FBMchat",
    "TBV_contact_us_showchat[DT_O_TOL_0s]":             "TBV-contact-us-showchat",
    "TBV_contact_us_botchat[DT_O_TOL_0s]":              "TBV-contact-us-botchat",
    "TBV_contact_us_FBMchat[DT_O_TOL_0s]":              "TBV-contact-us-FBMchat",
    "TBV_spa_contact_us[DT_E]":                         "TBV-spa-contact-us",
    "TBV_spa_contact_us_showchat[DT_S]":                "TBV-spa-contact-us-showchat",
    "TBV_spa_contact_us_botchat[DT_S]":                 "TBV-spa-contact-us-botchat",
    "TBV_spa_contact_us_FBMchat[DT_S]":                 "TBV-spa-contact-us-FBMchat",
    "TBV_spa_contact_us_showchat[DT_O_TOL_0s]":         "TBV-spa-contact-us-showchat",
    "TBV_spa_contact_us_botchat[DT_O_TOL_0s]":          "TBV-spa-contact-us-botchat",
    "TBV_spa_contact_us_FBMchat[DT_O_TOL_0s]":          "TBV-spa-contact-us-FBMchat",
    "PP_contact-us[DT_E]":                              "PP-contact-us",
    "PP_contact_us_showchat[DT_S]":                     "PP-contact-us-showchat",
    "PP_contact_us_botchat[DT_S]":                      "PP-contact-us-botchat",
    "PP_contact_us_FBMchat[DT_S]":                      "PP-contact-us-FBMchat",
    "PP_contact_us_showchat[DT_O_TOL_0s]":              "PP-contact-us-showchat",
    "PP_contact_us_botchat[DT_O_TOL_0s]":               "PP-contact-us-botchat",
    "PP_contact_us_FBMchat[DT_O_TOL_0s]":               "PP-contact-us-FBMchat",
    "PP_spa_contact_us[DT_E]":                          "PP-spa-contact-us",
    "PP_spa_contact_us_showchat[DT_S]":                 "PP-spa-contact-us-showchat",
    "PP_spa_contact_us_botchat[DT_S]":                  "PP-spa-contact-us-botchat",
    "PP_spa_contact_us_FBMchat[DT_S]":                  "PP-spa-contact-us-FBMchat",
    "PP_spa_contact_us_showchat[DT_O_TOL_0s]":          "PP-spa-contact-us-showchat",
    "PP_spa_contact_us_botchat[DT_O_TOL_0s]":           "PP-spa-contact-us-botchat",
    "PP_spa_contact_us_FBMchat[DT_O_TOL_0s]":           "PP-spa-contact-us-FBMchat",
    "WFM_contact-us[DT_E]":                             "WFM-contact-us",
    "WFM_contact_us_showchat[DT_S]":                    "WFM-contact-us-showchat",
    "WFM_contact_us_botchat[DT_S]":                     "WFM-contact-us-botchat",
    "WFM_contact_us_FBMchat[DT_S]":                     "WFM-contact-us-FBMchat",
    "WFM_contact_us_showchat[DT_O_TOL_0s]":             "WFM-contact-us-showchat",
    "WFM_contact_us_botchat[DT_O_TOL_0s]":              "WFM-contact-us-botchat",
    "WFM_contact_us_FBMchat[DT_O_TOL_0s]":              "WFM-contact-us-FBMchat",
    "WFM_spa_contact_us[DT_E]":                         "WFM-spa-contact-us",
    "WFM_spa_contact_us_showchat[DT_S]":                "WFM-spa-contact-us-showchat",
    "WFM_spa_contact_us_botchat[DT_S]":                 "WFM-spa-contact-us-botchat",
    "WFM_spa_contact_us_FBMchat[DT_S]":                 "WFM-spa-contact-us-FBMchat",
    "WFM_spa_contact_us_showchat[DT_O_TOL_0s]":         "WFM-spa-contact-us-showchat",
    "WFM_spa_contact_us_botchat[DT_O_TOL_0s]":          "WFM-spa-contact-us-botchat",
    "WFM_spa_contact_us_FBMchat[DT_O_TOL_0s]":          "WFM-spa-contact-us-FBMchat",

    "WFM_sales_why[DT_S]":                           "WFM-sales-why",
    "WFM_sales_why_no_contracts[DT_S]":              "WFM-sales-why-no-contracts",
    "WFM_sales_why_coverage[DT_S]":                  "WFM-sales-why-coverage",
    "WFM_sales_why_service_plans[DT_S]":             "WFM-sales-why-service-plans",
    "WFM_sales_why_multiline[DT_S]":                 "WFM-sales-why-multiline",
    "WFM_care_collectminpinpromo[DT_S]":             "WFM-care-collectminpinpromo",
    "WFM_care_autopay[DT_S]":                        "WFM-care-autopay",
    "WFM_sales_serviceplan[DT_S]":                   "WFM-sales-serviceplan",
    "WFM_sales_keep_your_own_phone[DT_S]":           "WFM-sales-keep-your-own-phone",
    "WFM_sales_intlcalling[DT_S]":                   "WFM-sales-internationalcalling",
    "WFM_care_activation_selectdevice[DT_S]":        "WFM-care-activation-selectdevice",
    "WFM_care_rewards[DT_S]":                        "WFM-care-rewards",
    "WFM_care_accountrecovery[DT_S]":                "WFM-care-accountrecovery",
    "WFM_sales_why[DT_O_TOL_30s]":                   "WFM-sales-why",
    "WFM_sales_why_no_contracts[DT_O_TOL_30s]":      "WFM-sales-why-no-contracts",
    "WFM_sales_why_coverage[DT_O_TOL_30s]":          "WFM-sales-why-coverage",
    "WFM_sales_why_service_plans[DT_O_TOL_30s]":     "WFM-sales-why-service-plans",
    "WFM_sales_why_multiline[DT_O_TOL_30s]":         "WFM-sales-why-multiline",
    "WFM_sales_serviceplan[DT_O_TOL_30s]":           "WFM-sales-serviceplan",
    "WFM_sales_keep_your_phone[DT_O_TOL_30s]":       "WFM-sales-keep-your-own-phone",
    "WFM_sales_intlcalling[DT_O_TOL_30s]":           "WFM-sales-internationalcalling",
    "WFM_sales_spa_why[DT_S]":                       "WFM-sales-spa-why",
    "WFM_sales_spa_why_no_contracts[DT_S]":          "WFM-sales-spa-why-no-contracts",
    "WFM_sales_spa_why_coverage[DT_S]":              "WFM-sales-spa-why-coverage",
    "WFM_sales_spa_why_service_plans[DT_S]":         "WFM-sales-spa-why-service-plans",
    "WFM_sales_spa_why_multiline[DT_S]":             "WFM-sales-spa-why-multiline",
    "WFM_care_spa_collectminpinpromo[DT_S]":         "WFM-care-spa-collectminpinpromo",
    "WFM_care_spa_autopay[DT_S]":                    "WFM-care-spa-autopay",
    "WFM_sales_spa_serviceplan[DT_S]":               "WFM-sales-spa-serviceplan",
    "WFM_sales_spa_keep_your_own_phone[DT_S]":       "WFM-sales-spa-keep-your-own-phone",
    "WFM_sales_spa_intlcalling[DT_S]":               "WFM-sales-spa-internationalcalling",
    "WFM_care_spa_activation_selectdevice[DT_S]":    "WFM-care-spa-activation-selectdevice",
    "WFM_care_spa_rewards[DT_S]":                    "WFM-care-spa-rewards",
    "WFM_care_spa_accountrecovery[DT_S]":            "WFM-care-spa-accountrecovery",
    "WFM_sales_spa_why[DT_O_TOL_30s]":               "WFM-sales-spa-why",
    "WFM_sales_spa_why_no_contracts[DT_O_TOL_30s]":  "WFM-sales-spa-why-no-contracts",
    "WFM_sales_spa_why_coverage[DT_O_TOL_30s]":      "WFM-sales-spa-why-coverage",
    "WFM_sales_spa_why_service_plans[DT_O_TOL_30s]": "WFM-sales-spa-why-service-plans",
    "WFM_sales_spa_why_multiline[DT_O_TOL_30s]":     "WFM-sales-spa-why-multiline",
    "WFM_sales_spa_serviceplan[DT_O_TOL_30s]":       "WFM-sales-spa-serviceplan",
    "WFM_sales_spa_keep_your_phone[DT_O_TOL_30s]":   "WFM-sales-spa-keep-your-own-phone",
    "WFM_sales_spa_intlcalling[DT_O_TOL_30s]":       "WFM-sales-spa-internationalcalling",
}

/* -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- */

const entryPoints = {
    "TF-sales-accessories":                        ["l1:tracfone", "l2:accessories"],
    "TF-sales-accessories-audio":                  ["l1:tracfone", "l2:accessories", "l3:audio"],
    "TF-sales-accessories-batteries":              ["l1:tracfone", "l2:accessories", "l3:batteries"],
    "TF-sales-accessories-cables":                 ["l1:tracfone", "l2:accessories", "l3:cables"],
    "TF-sales-accessories-cases":                  ["l1:tracfone", "l2:accessories", "l3:cases"],
    "TF-sales-spa-accessories":                    ["l1:tracfone", "l2:accessories", "spanish"],
    "TF-sales-spa-accessories-audio":              ["l1:tracfone", "l2:accessories", "l3:audio", "spanish"],
    "TF-sales-spa-accessories-batteries":          ["l1:tracfone", "l2:accessories", "l3:batteries", "spanish"],
    "TF-sales-spa-accessories-cables":             ["l1:tracfone", "l2:accessories", "l3:cables", "spanish"],
    "TF-sales-spa-accessories-cases":              ["l1:tracfone", "l2:accessories", "l3:cases", "spanish"],
    "TF-care-activation":                          ["l1:tracfone", "l2:activation"],
    "TF-care-activate-phones-landing-pho":         ["l1:tracfone", "L2:activate.phones.landing.selectvalidate"],
    "TF-care-activate-phones-esimnewact-sim":      ["l1:tracfone", "l2:activate.phones.esimnewact.simselection"],
    "TF-care-activate-phones-newact-esn":          ["l1:tracfone", "L2:activate.phones.newact.esn"],
    "TF-care-activate-byop-landing-pho":           ["l1:tracfone", "L2:activate.byop.landing.selectvalidate"],
    "TF-care-activate-byop-esimnewact-sim":        ["l1:tracfone", "l2:activate.byop.esimnewact.simselection"],
    "TF-care-spa-activation":                      ["l1:tracfone", "l2:activation", "spanish"],
    "TF-care-spa-activate-phones-lan-pho":         ["l1:tracfone", "L2:activate.phones.landing.selectvalidate", "spanish"],
    "TF-care-spa-activate-phones-esi-sim":         ["l1:tracfone", "l2:activate.phones.esimnewact.simselection", "spanish"],
    "TF-care-spa-activate-phones-newact-esn":      ["l1:tracfone", "L2:activate.phones.newact.esn", "spanish"],
    "TF-care-spa-activate-byop-lan-pho":           ["l1:tracfone", "L2:activate.byop.landing.selectvalidate", "spanish"],
    "TF-care-spa-activate-byop-esi-sim":           ["l1:tracfone", "l2:activate.byop.esimnewact.simselection", "spanish"],
    "TF-sales-deals":                              ["l1:tracfone", "l2:deals"],
    "TF-sales-deals-summer-time":                  ["l1:tracfone", "l2:deals", "l3:summer-time"],
    "TF-sales-deals-refurbished-phones":           ["l1:tracfone", "l2:deals", "l3:refurbished-phones"],
    "TF-sales-deals-clearance-sale":               ["l1:tracfone", "l2:deals", "l3:clearance-sale"],
    "TF-sales-deals-discounted-favorites":         ["l1:tracfone", "l2:deals", "l3:discounted-favorites"],
    "TF-sales-spa-deals":                          ["l1:tracfone", "l2:deals", "spanish"],
    "TF-sales-spa-deals-summer-time":              ["l1:tracfone", "l2:deals", "l3:summer-time", "spanish"],
    "TF-sales-spa-deals-refurbished-phones":       ["l1:tracfone", "l2:deals", "l3:refurbished-phones", "spanish"],
    "TF-sales-spa-deals-clearance-sale":           ["l1:tracfone", "l2:deals", "l3:clearance-sale", "spanish"],
    "TF-sales-spa-deals-discounted-favorites":     ["l1:tracfone", "l2:deals", "l3:discounted-favorites", "spanish"],
    "TF-sales-kyop":                               ["l1:tracfone", "l2:kyop"],
    "TF-sales-spa-kyop":                           ["l1:tracfone", "l2:kyop", "spanish"],
    "TF-care-login":                               ["l1:tracfone", "l2:login"],
    "TF-care-spa-login":                           ["l1:tracfone", "l2:login", "spanish"],
    "TF-sales-phone":                              ["l1:tracfone", "l2:phone"],
    "TF-sales-smartphones":                        ["l1:tracfone", "l2:smartphones"],
    "TF-sales-basic-phones":                       ["l1:tracfone", "l2:basic-phones"],
    "TF-sales-support-hearing-aid-comp":           ["l1:tracfone", "l2:support", "l3:hearing-aid-compatibility"],
    "TF-sales-spa-phone":                          ["l1:tracfone", "l2:phone", "spanish"],
    "TF-sales-spa-smartphones":                    ["l1:tracfone", "l2:smartphones", "spanish"],
    "TF-sales-spa-basic-phones":                   ["l1:tracfone", "l2:basic-phones", "spanish"],
    "TF-sales-acp":                                ["l1:tracfone", "l2:acp"],
    "TF-sales-handset-protection":                 ["l1:tracfone", "l2:handset-protection"],
    "TF-sales-idnotify":                           ["l1:tracfone", "l2:idnotify"],
    "TF-sales-phone-add-ons":                      ["l1:tracfone", "l2:phone-add-ons"],
    "TF-sales-phone-service-plans":                ["l1:tracfone", "l2:phone-service-plans"],
    "TF-sales-tracfone-extras":                    ["l1:tracfone", "l2:tracfone-extras"],
    "TF-sales-spa-acp":                            ["l1:tracfone", "l2:acp", "spanish"],
    "TF-sales-spa-handset-protection":             ["l1:tracfone", "l2:handset-protection", "spanish"],
    "TF-sales-spa-idnotify":                       ["l1:tracfone", "l2:idnotify", "spanish"],
    "TF-sales-spa-phone-add-ons":                  ["l1:tracfone", "l2:phone-add-ons", "spanish"],
    "TF-sales-spa-phone-service-plans":            ["l1:tracfone", "l2:phone-service-plans", "spanish"],
    "TF-sales-spa-tracfone-extras":                ["l1:tracfone", "l2:tracfone-extras", "spanish"],
    "TF-care-refill-refill-your-plan":             ["l1:tracfone", "l2:refill", "l3:refill-your-plan"],
    "TF-care-refill-auto-refill":                  ["l1:tracfone", "l2:refill", "l3:auto-refill"],
    "TF-care-spa-refill-refill-your-plan":         ["l1:tracfone", "l2:refill", "l3:refill-your-plan", "spanish"],
    "TF-care-spa-refill-auto-refill":              ["l1:tracfone", "l2:refill", "l3:auto-refill", "spanish"],
    "TF-sales-about-coverage":                     ["l1:tracfone", "l2:about", "l3:coverage"],
    "TF-sales-about-phones":                       ["l1:tracfone", "l2:about", "l3:phones"],
    "TF-sales-about-no-contract-plans":            ["l1:tracfone", "l2:about", "l3:no-contract-plans"],
    "TF-sales-about-international-calling":        ["l1:tracfone", "l2:about", "l3:international-calling"],
    "TF-sales-about-rewards":                      ["l1:tracfone", "l2:about", "l3:rewards"],
    "TF-sales-about-apps":                         ["l1:tracfone", "l2:about", "l3:apps"],
    "TF-sales-spa-about-coverage":                 ["l1:tracfone", "l2:about", "l3:coverage", "spanish"],
    "TF-sales-spa-about-phones":                   ["l1:tracfone", "l2:about", "l3:phones", "spanish"],
    "TF-sales-spa-about-no-contract-plans":        ["l1:tracfone", "l2:about", "l3:no-contract-plans", "spanish"],
    "TF-sales-spa-about-international-calling":    ["l1:tracfone", "l2:about", "l3:international", "spanish"],
    "TF-sales-spa-about-rewards":                  ["l1:tracfone", "l2:about", "l3:rewards", "spanish"],
    "TF-sales-spa-about-apps":                     ["l1:tracfone", "l2:about", "l3:apps", "spanish"],
    "TF-care-support-contact-us":                  ["l1:tracfone", "l2:support", "l3:contact-us"],
    "TF-care-support-contact-us-showchat":         ["l1:tracfone", "l2:support", "l3:contactus-611611"],
    "TF-care-support-contact-us-botchat":          ["l1:tracfone", "l2:support", "l3:contactus-bot"],
    "TF-care-support-contact-us-FBMchat":          ["l1:tracfone", "l2:support", "l3:contactus-fbmchat"],
    "TF-care-spa-support-contact-us":              ["l1:tracfone", "l2:support", "l3:contactus-611611", "spanish"],
    "TF-care-spa-support-contact-us-FBMchat":      ["l1:tracfone", "l2:support", "l3:contactus-bot", "spanish"],
    "TF-care-spa-support-contact-us-botchat":      ["l1:tracfone", "l2:support", "l3:contactus-fbmchat", "spanish"],
    "TF-sales-mobile-lp-chat":                     ["l1:tracfone", "l2:mobile-lp-chat"],
    "TF-sales-shop-cart":                          ["l1:tracfone", "l2:shop", "l3:cart"],
    "TF-sales-shop-checkout":                      ["L1:tracfone", "L2:shop", "L3:checkout"],
    "TF-sales-products-plansservices-phone":       ["L1:tracfone", "L2:products", "L3:plans-and-services", "L4:phone-service-plans.html"],
    "TF-sales-phone-pdp":                          ["l1:tracfone", "l2:phone", "pdp", "L3:moto-g-stylus-5g-2022-prep", "English", "GuestUser"],
    "GS-care-wps-portal-home-contact":             ["l1:gosmartmobile", "l2:contactus"],
    "GS-care-contactus-611611":                    ["l1:gosmartmobile", "l2:contactus-611611"],
    "GS-care-wps-portal-home-contact-bot":         ["l1:gosmartmobile", "l2:contactus-bot"],
    "GS-care-wps-portal-home-contact-fbmchat":     ["l1:gosmartmobile", "l2:contactus-fbmchat"],
    "GS-care-spa-wps-portal-home-contact":         ["l1:gosmartmobile", "l2:contactus"],
    "GS-care-spa-contactus-611611":                ["l1:gosmartmobile", "l2:contactus-611611", "spanish"],
    "GS-care-spa-wps-portal-home-contact-bot":     ["l1:gosmartmobile", "l2:contactus-bot", "spanish"],
    "GS-care-spa-wps-portal-home-contact-fbmchat": ["l1:gosmartmobile", "l2:contactus-fbmchat", "spanish"],
    "NT-care-serviceplan":                         ["l1:net10wireless", "l2:serviceplan"],
    "NT-care-contactus":                           ["l1:net10wireless", "l2:contactus"],
    "NT-sales-shop-ild":                           ["l1:net10wireless", "l2:shop", "L3:ild"],
    "NT-care-autorefill":                          ["l1:net10wireless", "l2:autorefill"],
    "NT-care-contactus-showchat":                  ["l1:net10wireless", "l2:contactus-611611"],
    "NT-care-contactus-botchat":                   ["l1:net10wireless", "l2:contactus-bot"],
    "NT-care-contactus-FBMchat":                   ["l1:net10wireless", "l2:contactus-fbmchat"],
    "NT-care-mobilechat":                          ["l1:net10wireless", "l2:mobile-lp-chat"],
    "NT-care-spa-serviceplan":                     ["l1:net10wireless", "l2:serviceplan", "spanish"],
    "NT-care-spa-contactus":                       ["l1:net10wireless", "l2:contactus", "spanish"],
    "NT-care-spa-shop-ild":                        ["l1:net10wireless", "l2:shop", "L3:ild", "spanish"],
    "NT-care-spa-autorefill":                      ["l1:net10wireless", "l2:autorefill", "spanish"],
    "NT-care-spa-contactus-showchat":              ["l1:net10wireless", "l2:contactus-611611", "spanish"],
    "NT-care-spa-contactus-botchat":               ["l1:net10wireless", "l2:contactus-bot", "spanish"],
    "NT-care-spa-contactus-FBMchat":               ["l1:net10wireless", "l2:contactus-fbmchat", "spanish"],
    "NT-care-spa-mobilechat":                      ["l1:net10wireless", "l2:mobile-lp-chat", "spanish"],

    "DP-Care-TBV":                                 ["tfdap", "tbv"],
    "DP-Care-AR":                                  ["tfdap", "ar"],

    "PP-contact-us":                               ["l1:pagepluscellular", "l2:support-contact"],
    "PP-contact-us-showchat":                      ["l1:pagepluscellular", "l2:support-contact", "l3:611611"],
    "PP-contact-us-botchat":                       ["l1:pagepluscellular", "l2:support-contact", "l3:botchat"],
    "PP-contact-us-FBMchat":                       ["l1:pagepluscellular", "l2:support-contact", "l3:fbmchat"],
    "PP-spa-contact-us":                           ["l1:pagepluscellular", "l2:support-contact", "spanish"],
    "PP-spa-contact-us-showchat":                  ["l1:pagepluscellular", "l2:support-contact", "l3:611611", "spanish"],
    "PP-spa-contact-us-botchat":                   ["l1:pagepluscellular", "l2:support-contact", "l3:botchat", "spanish"],
    "PP-spa-contact-us-FBMchat":                   ["l1:pagepluscellular", "l2:support-contact", "l3:fbmchat", "spanish"],

    "SL-Care":                                     ["l1:safelinkwireless", "enrollment", "contact us"],
    "SL-care-about-us":                            ["l1:safelinkwireless", "l2:support", "l3:aboutUs"],
    "SL-contact-us":                               ["l1:safelinkwireless", "l2:support", "l3:contact-us"],
    "SL-contact-us-showchat":                      ["l1:safelinkwireless", "l2:support", "l3:contactus-bot"],
    "SL-contact-us-botchat":                       ["l1:safelinkwireless", "l2:support", "l3:contactus-611611"],
    "SL-contact-us-FBMchat":                       ["l1:safelinkwireless", "l2:support", "l3:contactus-fbmchat"],
    "SL-spa-contact-us":                           ["l1:safelinkwireless", "l2:support", "l3:contact-us", "spanish"],
    "SL-spa-contact-us-showchat":                  ["l1:safelinkwireless", "l2:support", "l3:contactus-bot", "spanish"],
    "SL-spa-contact-us-botchat":                   ["l1:safelinkwireless", "l2:support", "l3:contactus-611611", "spanish"],
    "SL-spa-contact-us-FBMchat":                   ["l1:safelinkwireless", "l2:support", "l3:contactus-fbmchat", "spanish"],

    "SM-care-mobilechat":				           [ "l1:simplemobile", "l2:mobile-lp-chat" ],
    "SM-sales-shop-simplemobile-phones":           ["l1:simplemobile", "l2:phones"],
    "SM-sales-activation-byopcollectsim":          ["l1:simplemobile", "l2:activation", "l3:byopcollectsim"],
    "SM-sales-serviceplan":                        ["l1:simplemobile", "l2:serviceplan"],
    "SM-sales-shop-simplemobile-accessories":      ["l1:simplemobile", "l2:accessories"],
    "SM-sales-shop-simplemobile-datadevices":      ["l1:simplemobile", "l2:datadevices"],
    "SM-sales-acp":                                ["l1:simplemobile", "l2:acp"],
    "SM-care-protectyourphones-landing":           ["l1:simplemobile", "l2:protectyourphones", "l3:landing"],
    "SM-care-collectminpinpromo":                  ["l1:simplemobile", "l2:collectminpinpromo"],
    "SM-care-autorefill":                          ["l1:simplemobile", "l2:autorefill"],
    "SM-care-serviceplan-addons":                  ["l1:simplemobile", "l2:serviceplan", "l3:addons"],
    "SM-care-activation-selectdevice":             ["l1:simplemobile", "l2:activation", "l3:selectdevice"],
    "SM-sales-shop-simplemobile-deals":            ["l1:simplemobile", "l2:deals"],
    "SM-sales-why-sm":                             ["l1:simplemobile", "l2:why-simple-mobile"],
    "SM-sales-why-sm-no-contracts":                ["l1:simplemobile", "l2:why-simple-mobile", "l3:no-contracts"],
    "SM-sales-why-sm-unlimited-data":              ["l1:simplemobile", "l2:why-simple-mobile", "l3:unlimited-data"],
    "SM-sales-why-sm-keep-your-phone":             ["l1:simplemobile", "l2:why-simple-mobile", "l3:keep-your-phone"],
    "SM-sales-why-sm-lease-your-phone":            ["l1:simplemobile", "l2:why-simple-mobile", "l3:lease-your-phone"],
    "SM-sales-protectyourphones-landing":          ["l1:simplemobile", "l2:protectyourphones", "l3:landing"],
    "SM-sales-why-simple-mobile-intl":             ["l1:simplemobile", "l2:why-simple-mobile", "l3:international"],
    "SM-sales-why-simple-mobile-serviceplan":      ["l1:simplemobile", "l2:why-simple-mobile", "l3:serviceplan"],
    "SM-care-rewards":                             ["l1:simplemobile", "l2:rewards"],
    "SM-care-myaccount-login-collectusername":     ["l1:simplemobile", "l2:myaccount", "l3:login", "l4:collectusername"],
    "SM-spa-shop-simplemobile-phones":             ["l1:simplemobile", "l2:phones", "spanish"],
    "SM-sales-spa-activation-byopcollectsim":      ["l1:simplemobile", "l2:activation", "l3:byopcollectsim", "spanish"],
    "SM-sales-spa-serviceplan":                    ["l1:simplemobile", "l2:serviceplan", "spanish"],
    "SM-sales-spa-why-simple-mobile-intl":         ["l1:simplemobile", "l2:why-simple-mobile", "l3:international", "spanish"],
    "SM-care-spa-shop-en-sim-lea":                 ["l1:simplemobile", "l2:lease-deals", "spanish"],
    "SM-care-spa-protectyourphones-landing":       ["l1:simplemobile", "l2:protectyourphones", "l3:landing", "spanish"],
    "SM-sales-spa-shop-simplemobile-dat":          ["l1:simplemobile", "l2:datadevices", "spanish"],
    "SM-sales-spa-acp":                            ["l1:simplemobile", "l2:acp", "spanish"],
    "SM-care-spa-collectminpinpromo":              ["l1:simplemobile", "l2:collectminpinpromo", "spanish"],
    "SM-care-spa-autorefill":                      ["l1:simplemobile", "l2:autorefill", "spanish"],
    "SM-care-spa-serviceplan-addons":              ["l1:simplemobile", "l2:serviceplan", "l3:addons", "spanish"],
    "SM-care-spa-activation-selectdevice":         ["l1:simplemobile", "l2:activation", "l3:selectdevice", "spanish"],
    "SM-sales-spa-why-sm":                         ["l1:simplemobile", "l2:why-simple-mobile", "spanish"],
    "SM-sales-spa-why-sm-no-contracts":            ["l1:simplemobile", "l2:why-simple-mobile", "l3:no-contracts", "spanish"],
    "SM-sales-spa-why-sm-unlimited-data":          ["l1:simplemobile", "l2:why-simple-mobile", "l3:unlimited-data", "spanish"],
    "SM-sales-spa-why-sm-keep-your-phone":         ["l1:simplemobile", "l2:why-simple-mobile", "l3:keep-your-phone", "spanish"],
    "SM-sales-spa-why-sm-lease-your-phone":        ["l1:simplemobile", "l2:why-simple-mobile", "l3:lease-your-phone", "spanish"],
    "SM-sales-spa-protectyourphones-landing":      ["l1:simplemobile", "l2:protectyourphones", "l3:landing", "spanish"],
    "SM-sales-spa-why-simple-mobile-serviceplan":  ["l1:simplemobile", "l2:why-simple-mobile", "l3:serviceplan", "spanish"],
    "SM-care-spa-rewards":                         ["l1:simplemobile", "l2:rewards", "spanish"],
    "SM-care-spa-myaccount-login-col":             ["l1:simplemobile", "l2:myaccount", "l3:login", "l4:collectusername", "spanish"],
    "SM-contact-us":                               ["l1:simplemobile", "l2:contactus"],
    "SM-contact-us-showchat":                      ["l1:simplemobile", "l2:contactus-611611"],
    "SM-contact-us-botchat":                       ["l1:simplemobile", "l2:contactus-bot"],
    "SM-contact-us-FBMchat":                       ["l1:simplemobile", "l2:contactus-fbmchat"],
    "SM-spa-contact-us":                           ["l1:simplemobile", "l2:contactus", "spanish"],
    "SM-spa-contact-us-showchat":                  ["l1:simplemobile", "l2:contactus-611611", "spanish"],
    "SM-spa-contact-us-botchat":                   ["l1:simplemobile", "l2:contactus-bot", "spanish"],
    "SM-spa-contact-us-FBMchat":                   ["l1:simplemobile", "l2:contactus-fbmchat", "spanish"],
    "ST-5g":                                       ["l1:straighttalk", "l2:5g"],
    "ST-all-plans":                                ["l1:straighttalk", "l2:all-plans"],
    "ST-plans-wireless-phones":                    ["l1:straighttalk", "l2:plans", "l3:wireless-phones"],
    "ST-plans-home-phones":                        ["l1:straighttalk", "l2:plans", "l3:home-phones"],
    "ST-plans-add-ons":                            ["l1:straighttalk", "l2:plans", "l3:add-ons"],
    "ST-acp":                                      ["l1:straighttalk", "l2:acp"],
    "ST-plans-home-internet-plans":                ["l1:straighttalk", "l2:plans", "l3:home-internet-plans"],
    "ST-plans-tablets":                            ["l1:straighttalk", "l2:plans", "l3:tablets"],
    "ST-plans-hotspots":                           ["l1:straighttalk", "l2:plans", "l3:hotspots"],
    "ST-handset-protection-mobile-protect":        ["l1:straighttalk", "l2:handset-protection", "l3:mobile-protect"],
    "ST-extras-international-long-distance":       ["l1:straighttalk", "l2:extras", "l3:international-long-distance"],
    "ST-extras-cloud-services":                    ["l1:straighttalk", "l2:extras", "l3:cloud-services"],
    "ST-extras-idnotify":                          ["l1:straighttalk", "l2:extras", "l3:idnotify"],
    "ST-all-phones":                               ["l1:straighttalk", "l2:all-phones"],
    "ST-phones-ios-phones":                        ["l1:straighttalk", "l2:phones", "l3:ios-phones"],
    "ST-phones-android":                           ["l1:straighttalk", "l2:phones", "l3:android"],
    "ST-phones-basic-phones":                      ["l1:straighttalk", "l2:phones", "l3:basic-phones"],
    "ST-phones-home-phones":                       ["l1:straighttalk", "l2:phones", "l3:home-phones"],
    "ST-phones-5g-phones":                         ["l1:straighttalk", "l2:phones", "l3:5g-phones"],
    "ST-all-devices":                              ["l1:straighttalk", "l2:all-devices"],
    "ST-devices-home-internet":                    ["l1:straighttalk", "l2:devices", "l3:home-internet"],
    "ST-devices-wifi-hotspots":                    ["l1:straighttalk", "l2:devices", "l3:wifi-hotspots"],
    "ST-devices-phone-sim-cards":                  ["l1:straighttalk", "l2:devices", "l3:phone-sim-cards"],
    "ST-devices-tablet-sim-cards":                 ["l1:straighttalk", "l2:devices", "l3:tablet-sim-cards"],
    "ST-all-accessories":                          ["l1:straighttalk", "l2:all-accessories"],
    "ST-accessories-batteries":                    ["l1:straighttalk", "l2:accessories", "l3:batteries"],
    "ST-accessories-cables":                       ["l1:straighttalk", "l2:accessories", "l3:cables"],
    "ST-accessories-audio":                        ["l1:straighttalk", "l2:accessories", "l3:audio"],
    "ST-accessories-cases-protection":             ["l1:straighttalk", "l2:accessories", "l3:cases-protection"],
    "ST-more-options-trade-in-program":            ["l1:straighttalk", "l2:more-options", "l3:trade-in-program"],
    "ST-more-options-phone-payment-plan":          ["l1:straighttalk", "l2:more-options", "l3:phone-payment-plan"],
    "ST-5g-lte-home-internet":                     ["l1:straighttalk", "l2:5g-lte-home-internet"],
    "ST-deals-all-deals":                          ["l1:straighttalk", "l2:deals", "l3:all-deals"],
    "ST-deals-clearance-sale":                     ["l1:straighttalk", "l2:deals", "l3:clearance-sale"],
    "ST-deals-popular-deals":                      ["l1:straighttalk", "l2:deals", "l3:popular-deals"],
    "ST-deals-refurbished-phones":                 ["l1:straighttalk", "l2:deals", "l3:refurbished-phones"],
    "ST-deals-holiday-marketplace-phones":         ["l1:straighttalk", "l2:deals", "l3:holiday", "l4:marketplace-phones"],
    "ST-deals-holiday-summer-time":                ["l1:straighttalk", "l2:deals", "l3:holiday", "l4:summer-time"],
    "ST-refill-refill-your-plan":                  ["l1:straighttalk", "l2:refill", "l3:refill-your-plan"],
    "ST-refill-auto-refill":                       ["l1:straighttalk", "l2:refill", "l3:auto-refill"],
    "ST-activate.phones.landing.phoneno":          ["l1:straighttalk", "l2:activate.phones.landing.phoneno"],
    "ST-activate.byop.landing.phoneno":            ["l1:straighttalk", "l2:activate.byop.landing.phoneno"],
    "ST-activate.device.landing.esn":              ["l1:straighttalk", "l2:activate.device.landing.esn"],
    "ST-whyst-phones":                             ["l1:straighttalk", "l2:whyst", "l3:phones"],
    "ST-whyst-plans":                              ["l1:straighttalk", "l2:whyst", "l3:plans"],
    "ST-whyst-keep-your-own-phone":                ["l1:straighttalk", "l2:whyst", "l3:keep-your-own-phone"],
    "ST-whyst-coverage":                           ["l1:straighttalk", "l2:whyst", "l3:coverage"],
    "ST-spa-5g":                                   ["l1:straighttalk", "l2:5g", "spanish"],
    "ST-care-support-contact-us":                  ["l1:straighttalk", "l2:support", "l3:contact"],
    "ST-care-support-contact-us-showchat":         ["l1:straighttalk", "l2:support", "l3:contact-611611"],
    "ST-care-support-contact-us-botchat":          ["l1:straighttalk", "l2:support", "l3:contact-bot"],
    "ST-care-support-contact-us-FBMchat":          ["l1:straighttalk", "l2:support", "l3:contact-fbmchat"],
    "ST-care-spa-support-contact-us":              ["l1:straighttalk", "l2:support", "l3:contact", "spanish"],
    "ST-care-spa-support-contact-us-showchat":     ["l1:straighttalk", "l2:support", "l3:contact-611611", "spanish"],
    "ST-care-spa-support-contact-us-botchat":      ["l1:straighttalk", "l2:support", "l3:contact-bot", "spanish"],
    "ST-care-spa-support-contact-us-FBMchat":      ["l1:straighttalk", "l2:support", "l3:contact-fbmchat", "spanish"],
    "TBV-sales-plans":                             ["l1:totalbyverizon", "l2:plans"],
    "TBV-sales-all-phones":                        ["l1:totalbyverizon", "l2:all-phones"],
    "TBV-sales-kyop":                              ["l1:totalbyverizon", "l2:kyop"],
    "TBV-sales-smartphones":                       ["l1:totalbyverizon", "l2:smartphones"],
    "TBV-sales-basic-phones":                      ["l1:totalbyverizon", "l2:basic-phones"],
    "TBV-sales-accessories":                       ["l1:totalbyverizon", "l2:accessories"],
    "TBV-sales-deals":                             ["l1:totalbyverizon", "l2:deals"],
    "TBV-sales-extras-disney-plus":                ["l1:totalbyverizon", "l2:extras", "l3:disney-plus"],
    "TBV-care-plans-global-calling-card":          ["l1:totalbyverizon", "l2:plans", "l3:global-calling-card"],
    "TBV-care-international-calling-destinations": ["l1:totalbyverizon", "l2:international-calling-destinations"],
    "TBV-care-refill-refill-your-plan":            ["l1:totalbyverizon", "l2:refill", "l3:refill-your-plan"],
    "TBV-care-activation":                         ["l1:totalbyverizon", "l2:activation"],
    "TBV-care-activate-phones-landing-phoneno":    ["l1:totalbyverizon", "l2:activate-phones-landing-phoneno"],
    "TBV-care-activate-byop-landing-phoneno":      ["l1:totalbyverizon", "l2:activate-byop-landing-phoneno"],
    "TBV-care-activate-device-landing-esn":        ["l1:totalbyverizon", "l2:activate-device-landing-esn"],
    "TBV-sales-about-coverage":                    ["l1:totalbyverizon", "l2:about", "l3:coverage"],
    "TBV-sales-about-no-contract-phone-plans":     ["l1:totalbyverizon", "l2:about", "l3:no-contract-phone-plans"],
    "TBV-sales-about-prepaid-phones":              ["l1:totalbyverizon", "l2:about", "l3:prepaid-phones"],
    "TBV-care-my-account-my-rewards":              ["l1:totalbyverizon", "l2:my-account", "l3:my-rewards"],
    "TBV-care-mobilechat":                         [ "l1:totalbyverizon", "l2:mobile-lp-chat" ],

    "TBV-contact-us":                              ["l1:totalbyverizon", "l2:support", "l3:contact-us"],
    "TBV-contact-us-showchat":                     ["l1:totalbyverizon", "l2:support", "l3:contactus-611611"],
    "TBV-contact-us-botchat":                      ["l1:totalbyverizon", "l2:support", "l3:contactus-bot"],
    "TBV-contact-us-FBMchat":                      ["l1:totalbyverizon", "l2:support", "l3:contactus-fbmchat"],
    "TBV-spa-contact-us":                          ["l1:totalbyverizon", "l2:support", "l3:contact-us", "spanish"],
    "TBV-spa-contact-us-showchat":                 ["l1:totalbyverizon", "l2:support", "l3:contactus-611611", "spanish"],
    "TBV-spa-contact-us-botchat":                  ["l1:totalbyverizon", "l2:support", "l3:contactus-bot", "spanish"],
    "TBV-spa-contact-us-FBMchat":                  ["l1:totalbyverizon", "l2:support", "l3:contactus-fbmchat", "spanish"],
    "WFM-sales-why":                               ["l1:myfamilymobile", "l2:why"],
    "WFM-sales-why-no-contracts":                  ["l1:myfamilymobile", "l2:why", "l3:no-contracts"],
    "WFM-sales-why-coverage":                      ["l1:myfamilymobile", "l2:why", "l3:coverage"],
    "WFM-sales-why-service-plans":                 ["l1:myfamilymobile", "l2:why", "l3:service-plans"],
    "WFM-sales-why-multiline":                     ["l1:myfamilymobile", "l2:why", "l3:multiline"],
    "WFM-care-collectminpinpromo":                 ["l1:myfamilymobile", "l2:collectminpinpromo"],
    "WFM-care-autopay":                            ["l1:myfamilymobile", "l2:autopay"],
    "WFM-sales-serviceplan":                       ["l1:myfamilymobile", "l2:serviceplan"],
    "WFM-sales-keep-your-own-phone":               ["l1:myfamilymobile", "l2:keep-your-own-phone"],
    "WFM-sales-internationalcalling":              ["l1:myfamilymobile", "l2:internationalcalling"],
    "WFM-care-activation-selectdevice":            ["l1:myfamilymobile", "l2:activation", "l3:selectdevice"],
    "WFM-care-rewards":                            ["l1:myfamilymobile", "l2:rewards"],
    "WFM-care-accountrecovery":                    ["l1:myfamilymobile", "l2:accountrecovery"],
    "WFM-sales-spa-why":                           ["l1:myfamilymobile", "l2:why", "spanish"],
    "WFM-sales-spa-why-no-contracts":              ["l1:myfamilymobile", "l2:why", "l3:no-contracts", "spanish"],
    "WFM-sales-spa-why-coverage":                  ["l1:myfamilymobile", "l2:why", "l3:coverage", "spanish"],
    "WFM-sales-spa-why-service-plans":             ["l1:myfamilymobile", "l2:why", "l3:service-plans", "spanish"],
    "WFM-sales-spa-why-multiline":                 ["l1:myfamilymobile", "l2:why", "l3:multiline", "spanish"],
    "WFM-care-spa-collectminpinpromo":             ["l1:myfamilymobile", "l2:collectminpinpromo", "spanish"],
    "WFM-care-spa-autopay":                        ["l1:myfamilymobile", "l2:autopay", "spanish"],
    "WFM-sales-spa-serviceplan":                   ["l1:myfamilymobile", "l2:serviceplan", "spanish"],
    "WFM-sales-spa-keep-your-own-phone":           ["l1:myfamilymobile", "l2:keep-your-own-phone", "spanish"],
    "WFM-sales-spa-internationalcalling":          ["l1:myfamilymobile", "l2:internationalcalling", "spanish"],
    "WFM-care-spa-activation-selectdevice":        ["l1:myfamilymobile", "l2:activation", "l3:selectdevice", "spanish"],
    "WFM-care-spa-rewards":                        ["l1:myfamilymobile", "l2:rewards", "spanish"],
    "WFM-care-spa-accountrecovery":                ["l1:myfamilymobile", "l2:accountrecovery", "spanish"],

    "WFM-contact-us":              ["l1:myfamilymobile", "l2:contactus"],
    "WFM-contact-us-showchat":     ["l1:myfamilymobile", "l2:contactus-611611"],
    "WFM-contact-us-botchat":      ["l1:myfamilymobile", "l2:contactus-bot"],
    "WFM-contact-us-FBMchat":      ["l1:myfamilymobile", "l2:contactus-fbmchat"],
    "WFM-spa-contact-us":          ["l1:myfamilymobile", "l2:contactus", "spanish"],
    "WFM-spa-contact-us-showchat": ["l1:myfamilymobile", "l2:contactus-611611"],
    "WFM-spa-contact-us-botchat":  ["l1:myfamilymobile", "l2:contactus-bot", "spanish"],
    "WFM-spa-contact-us-FBMchat":  ["l1:myfamilymobile", "l2:contactus-fbmchat", "spanish"],

}


const verizonBrand = [
    {
        name:         "net10",
        engagementId: "4080717838",
        fontFamily:   "Roboto",
        fontSize:     "14px",
        colors:       [{blue: "00AEEF"}, {simpleBlack: "231F20"}, {white: "FFFFFF"}, {hover: "F3FCFF"}]
    }
    ,
    {
        name:         "net10support",
        engagementId: "4144064438",
        fontFamily:   "Roboto",
        fontSize:     "14px",
        colors:       [{blue: "00AEEF"}, {simpleBlack: "231F20"}, {white: "FFFFFF"}, {hover: "F3FCFF"}]
    },
    // missing
    {
        name:         "safelink",
        engagementId: "4080697738",
        fontFamily:   "Arial",
        fontSize:     "",
        colors:       [{"1": "000000"}, {"2": "000000"}, {"3": "000000"}]
    },
    // missing
    {
        name:         "pageplus",
        engagementId: "4080722538",
        fontFamily:   "Arial",
        fontSize:     "",
        colors:       [{"1": "dd1e1e"}, {"2": "000000"}, {"3": "000000"}]
    },
    {
        name:         "familymobile",
        engagementId: "4080715538",
        fontFamily:   "Bogle regular",
        fontSize:     "14px",
        colors:       [{walmartBlue: "1A75CF"}, {walmartYellow: "F7B512"}, {white: "FFFFFF"}]
    },
    {
        name:         "simple",
        engagementId: "4080674538",
        fontFamily:   "Montserrat",
        fontSize:     "14px",
        colors:       [{simpleGreen: "93D500"}, {simpleBlack: "231F20"}, {white: "FFFFFF"}]
    },
    {
        name:         "straighttalk",
        engagementId: "4080561538",
        fontFamily:   "Segoe UI regular",
        fontSize:     "14px",
        colors:       [{green: "BEE81E"}, {white: "FFFFFF"}, {black: "000000"}, {grey: "6C6C6C"}]
    },
    {
        name:         "tracfone",
        engagementId: "4089582738",
        fontFamily:   "Lato Bold",
        fontSize:     "",
        colors:       [{tracfoneBlue: "273691"}, {tracfoneGreen: "88C65B"}, {lightestGrey: "F6F9FC"}, {lightGrey: "E3E9EF"}, {hoverBlue: "012979"}]
    },
    // red:  RGB:238,0,0  =  ee0000
    {
        name:         "total",
        engagementId: "4080697138",
        fontFamily:   "Verizon",
        fontSize:     "",
        colors:       [{black: "000000"}, {white: "FFFFFF"}, {red: "RGB:238,0,0"}]
    },
    {
        name:         "gosmart",
        engagementId: "4127275338",
        fontFamily:   "Istok Web",
        fontSize:     "14px",
        colors:       [{blue: "048FB6"}, {darkGray: "414143"}, {white: "FFFFFF"}, {logoGreen: "BDD531"}, {hoverBlue: "048FB6"}]
    }
]

export {
    engagements,
    entryPoints,
    verizonBrand
}